### ISSUE TITLE
能写一段 Contributor Guide 简述一下参与翻译的方法吗？

### ISSUE THREAD

**Issue by 1c7** [jinyulei0710/The-Busy-Coder-s-Guide-to-Android-Development#1]
比如英文原文链接是啥。
协作翻译的大概流程。
诸如此类的。

**Comment by jinyulei0710** [comment]
http://pan.baidu.com/s/1skTs46x 这是英文原版书的下载地址。目前还没人要参加，所以并没有明确的协作流程。

**Comment by 1c7** [comment]
@jinyulei0710  感谢回复。
你定一个协作流程，这样别人看了才知道怎么参加嘛，之后才会有人参加。
比如现在我想参与翻译的话，我到底怎么做算是合适呢？不知道。
现在的目录结构我还没细看，是每一章都对应一个文件夹，
然后我只要 fork 下来翻译完了改下对应章节下的 readme 然后 pull request?

**Comment by jinyulei0710** [comment]
@1c7 多谢提醒详见readme

**Comment by 1c7** [comment]
jinyulei0710  我说下我的理解你看看对不对，
1 先 fork 
2 在翻译前先修改 根目录下的 readme ，指明要翻译的地方，避免重复翻译
3 然后打开对应章节文件夹翻译
4 完了就去改 tableofContent 那个 readme，把连接挂上去
<br/>
<br/>

#### 另外

我看了下，现在 tableofContent 里有翻译完的目录，但问题是看的很累，为了便于分工翻译分的目录，在读者这边造成障碍，老是点进去，看完，退回来，点下一章。

<br/>
看云：http://www.kancloud.cn/
GitBook： https://www.gitbook.com/
<br/>

看云免费版的，书大小超过50M要买容量，10块钱50M，感觉这书这么厚肯定要花钱了，觉得不怎么值得花这个钱。
Gitbook 没被墙，速度可以，免费。我个人建议用这个。主要解决了读起来困难的问题。老是手动点点点很累的。对翻译者来说我也感觉方便多了。不用老是 add commit push。

如果最后能出版赚个零食钱感觉也是不错的。

**Comment by jinyulei0710** [comment]
@1c7 已经放到gitbook了
